"""
robots.txt for crawlers.

Without a robots.txt there is nothing that tells a crawler where the sitemap of
published datasets is. Every link into the app is generated by JavaScript, so a
crawler that does not execute it cannot discover a published dataset by
following links, and the sitemap is the only way it will find them.

Crawling is not restricted for anything that carries indexable content. Private
datasets need authentication and are therefore not a matter for robots.txt; the
paths that are excluded below are the ones where crawling is simply pointless.
"""

from django.conf import settings
from django.http import HttpResponse
from django.urls import NoReverseMatch, reverse

# Paths which serve no indexable content: administrative interfaces, the
# authentication flow, machine-readable API schemas and health checks.
DISALLOWED_PATHS = [
    "/accounts/",
    "/api/schema/",
    "/inbox/",
    "/watchman/",
]


def _disallowed_paths():
    """Return the paths to exclude, including the configurable admin URL."""
    paths = list(DISALLOWED_PATHS)
    admin_url = getattr(settings, "ADMIN_URL", None)
    if admin_url:
        paths.append("/" + admin_url.lstrip("/"))
    return sorted(paths)


def _sitemap_url(request):
    """Return the absolute URL of the sitemap, or None if there is none.

    The sitemap belongs to the publication plugin, which is optional: whether
    it is installed depends on `TOPOBANK_PLUGINS`. An instance running without
    it has no published datasets and hence nothing to advertise.
    """
    try:
        return request.build_absolute_uri(reverse("publication:sitemap"))
    except NoReverseMatch:
        return None


def robots_txt(request):
    """Serve robots.txt, pointing at the sitemap of published datasets."""
    lines = ["User-agent: *"]
    lines.extend(f"Disallow: {path}" for path in _disallowed_paths())

    sitemap_url = _sitemap_url(request)
    if sitemap_url is not None:
        lines.append("")
        lines.append(f"Sitemap: {sitemap_url}")

    return HttpResponse("\n".join(lines) + "\n", content_type="text/plain")
