"""Tests for robots.txt.

Every link into the app is generated by JavaScript, so the sitemap is the only
way a crawler can discover a published dataset. Without a robots.txt nothing
tells it where that sitemap is, see
https://github.com/ContactEngineering/topobank-publication/issues/21.
"""

import pytest
from django.urls import NoReverseMatch, reverse


def _sitemap_path():
    """Return the sitemap path, or None if the installed plugin has none."""
    try:
        return reverse("publication:sitemap")
    except NoReverseMatch:
        return None


# The sitemap route is provided by topobank-publication. It only exists from the
# release that added it onwards, and the plugin is optional in the first place.
requires_sitemap = pytest.mark.skipif(
    _sitemap_path() is None,
    reason="installed topobank-publication provides no sitemap route",
)


@pytest.fixture
def robots(db, client):
    """The parsed lines of robots.txt."""
    response = client.get("/robots.txt")
    assert response.status_code == 200
    assert response["Content-Type"] == "text/plain"
    return response.content.decode().splitlines()


def test_robots_txt_is_served_as_plain_text(robots):
    assert robots[0] == "User-agent: *"


@requires_sitemap
def test_sitemap_is_advertised_with_an_absolute_url(robots):
    sitemap_lines = [line for line in robots if line.startswith("Sitemap: ")]

    assert sitemap_lines == ["Sitemap: http://testserver" + _sitemap_path()]


def test_admin_url_is_disallowed(robots, settings):
    assert f"Disallow: /{settings.ADMIN_URL.lstrip('/')}" in robots


def test_pointless_paths_are_disallowed(robots):
    for path in ["/accounts/", "/api/schema/", "/inbox/", "/watchman/"]:
        assert f"Disallow: {path}" in robots


def test_published_datasets_are_not_disallowed(robots):
    """The whole point is to get published datasets crawled."""
    disallowed = [line[len("Disallow: "):] for line in robots
                  if line.startswith("Disallow: ")]

    assert "/" not in disallowed
    assert not any(path.startswith("/go/") for path in disallowed)
    assert not any(path.startswith("/ui/") for path in disallowed)


def test_sitemap_is_omitted_when_publications_are_not_installed(db, client, mocker):
    """The publication plugin is optional, see `TOPOBANK_PLUGINS`."""
    from django.urls import NoReverseMatch

    mocker.patch("ce_ui.robots.reverse", side_effect=NoReverseMatch)

    response = client.get("/robots.txt")

    assert response.status_code == 200
    assert "Sitemap:" not in response.content.decode()
    assert "User-agent: *" in response.content.decode()
